DROP SEQUENCE IF EXISTS Person_persnr_seq CASCADE;
DROP SEQUENCE IF EXISTS Standort_sid_seq CASCADE;

DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Spieler CASCADE;
DROP TABLE IF EXISTS Standort CASCADE;
DROP TABLE IF EXISTS Trainer CASCADE;
DROP TABLE IF EXISTS Angestellter CASCADE;
DROP TABLE IF EXISTS Mannschaft CASCADE;
DROP TABLE IF EXISTS Mitglied CASCADE;
DROP TABLE IF EXISTS Spiel CASCADE;
DROP TABLE IF EXISTS SpielerInMannschaft CASCADE;
DROP TABLE IF EXISTS BeteiligteSpieler CASCADE;
DROP TABLE IF EXISTS FanClub CASCADE;
DROP TABLE IF EXISTS Zeitraum CASCADE;
